# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
registries:
  nexus-internal:
    type: maven-repository
    url: https://nexus-internal.cloudbees.com/content/groups/mirror
    username: ${{secrets.NEXUS_INTERNAL_USERNAME}}
    password: ${{secrets.NEXUS_INTERNAL_PASSWORD}}
updates:
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
      time: "09:55"
      timezone: "Europe/Paris"
